
-- 기존 테이블이 있으면 삭제 후 재생성 (로컬·데모용, 선택 실행)
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE FOLLOW';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE ACCOUNT (
                         ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         USERNAME   VARCHAR2(255) NOT NULL,
                         CONSTRAINT UK_ACCOUNT_USERNAME UNIQUE (USERNAME)
);


CREATE TABLE FOLLOW (
                        FROM_ACCOUNT_ID  NUMBER NOT NULL,
                        TO_ACCOUNT_ID   NUMBER NOT NULL,
                        CONSTRAINT PK_FOLLOW PRIMARY KEY (FROM_ACCOUNT_ID, TO_ACCOUNT_ID),
                        CONSTRAINT FK_FOLLOW_FROM FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNT (ID),
                        CONSTRAINT FK_FOLLOW_TO   FOREIGN KEY (TO_ACCOUNT_ID)   REFERENCES ACCOUNT (ID)
);

-- ---------------------------------------------------------------------------
-- 더미 데이터 (기존 테이블이 이미 있을 때는 위 DROP/CREATE 없이 이 부분만 실행 가능)
-- ---------------------------------------------------------------------------

DELETE FROM FOLLOW;
DELETE FROM ACCOUNT;

INSERT INTO ACCOUNT (USERNAME) VALUES ('alice');
INSERT INTO ACCOUNT (USERNAME) VALUES ('bob');
INSERT INTO ACCOUNT (USERNAME) VALUES ('charlie');
INSERT INTO ACCOUNT (USERNAME) VALUES ('devyummi');
INSERT INTO ACCOUNT (USERNAME) VALUES ('xxxjjhhh');
INSERT INTO ACCOUNT (USERNAME) VALUES ('eve');
INSERT INTO ACCOUNT (USERNAME) VALUES ('frank');

INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'alice' AND b.username = 'bob';
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'alice' AND b.username = 'charlie';
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'bob' AND b.username = 'charlie';
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'devyummi' AND b.username = 'xxxjjhhh';
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'charlie' AND b.username = 'devyummi';
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'xxxjjhhh' AND b.username = 'eve';
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'alice' AND b.username = 'devyummi';
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id FROM ACCOUNT a, ACCOUNT b WHERE a.username = 'eve' AND b.username = 'frank';

COMMIT;
