
-- 기존 테이블이 있으면 삭제 후 재생성 (로컬·데모용, 선택 실행)
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE FOLLOW';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE ACCOUNT (
                         ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         USERNAME   VARCHAR2(255) NOT NULL,
                         CONSTRAINT UK_ACCOUNT_USERNAME UNIQUE (USERNAME)
);


CREATE TABLE FOLLOW (
                        FROM_ACCOUNT_ID  NUMBER NOT NULL,
                        TO_ACCOUNT_ID   NUMBER NOT NULL,
                        CONSTRAINT PK_FOLLOW PRIMARY KEY (FROM_ACCOUNT_ID, TO_ACCOUNT_ID),
                        CONSTRAINT FK_FOLLOW_FROM FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNT (ID),
                        CONSTRAINT FK_FOLLOW_TO   FOREIGN KEY (TO_ACCOUNT_ID)   REFERENCES ACCOUNT (ID)
);

-- ---------------------------------------------------------------------------
-- 더미 데이터 (기존 테이블이 이미 있을 때는 위 DROP/CREATE 없이 이 부분만 실행 가능)
-- ACCOUNT 1만 건 + FOLLOW 1만 건
-- ---------------------------------------------------------------------------

DELETE FROM FOLLOW;
DELETE FROM ACCOUNT;

-- ACCOUNT 10,000건: user00001 ~ user10000
INSERT INTO ACCOUNT (USERNAME)
SELECT 'user' || LPAD(LEVEL, 5, '0') FROM DUAL CONNECT BY LEVEL <= 10000;

-- FOLLOW 10,000건: ACCOUNT 실제 ID 기준으로 계정 i → 계정 i+1 (마지막→첫번째).
-- IDENTITY가 1부터가 아니어도 항상 삽입된 계정 ID와 일치함.
INSERT INTO FOLLOW (FROM_ACCOUNT_ID, TO_ACCOUNT_ID)
SELECT a.id, b.id
FROM (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM ACCOUNT
) a
JOIN (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM ACCOUNT
) b ON b.rn = MOD(a.rn, 10000) + 1
WHERE a.rn <= 10000;

COMMIT;
